os: linux
dist: bionic
jdk: oraclejdk11
language: java
branches:
  only:
  - master
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
script:
  - "./gradlew test jacocoTestCoverageVerification sonarqube build --stacktrace"

addons:
  sonarcloud:
    organization: "sergiosg"
    token:
      secure: "CRjzXzeZl796fmMF/glg0OWxqY1wIqFK667WDRzLBispQZbdND7EOp/oEPRO0bb4gK6rgGNTVMTfFWkZQU75JJ/jvKK/a6YvxS/9NLmzXn6pLe1eIpVg7ynoshYjYRryDOhnuAxDiSb8SfJpT8nppsCgyvAGhYVJDuM/hhvK/GjRr3Pu+FacTf9LbNarjlta+/NgWVg5rii10DdeM9QEEiTOqZ+O03rNXSmbzxxAtCy3/SfV61yIGMmKd/Wlft+dxxSdb7wQqT/5g6xIz5WPb/TgD3yYrAfe2iLseBQrYijgeUZROMqEtYBH2Dkar5HVK9VQR2vtQHyxPufzZzzinyjTvAwbnRvuvqfNH31ou9lNSpxfH5qBMZh0AlqhH0ABzM6rpO1JSXDP4JpOgvej+euWdu85pcvxM9NRk1Xjl602xQT9136IH8bQcXhOxdfhR50a4iymRkoA9GiTa74xVkfwvtim+hi4gooVNqGwpCYug1TQrTj/TvwqMCW+nzCk40Fscvhe4kjxCYPHv6JfCgPwVvVmZpqOYwdB1oLoAyXXWKuLIfFmhc5jJhD1PsZfyNqnG7wrID3eZ50Q5Xy+AegO/2bLK70ONC1m4P6pGCpTEGg8Rmz32LDZrcEDDcD8PQUf1HuSiOJlW+TflMtUvfIhDWJiGG1uyI7iyEX8OlI="


